#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x8F0871F202119294 (tom@stellard.net)
#
Name     : compat-llvm-soname5
Version  : 5.0.1
Release  : 1
URL      : http://releases.llvm.org/5.0.1/llvm-5.0.1.src.tar.xz
Source0  : http://releases.llvm.org/5.0.1/llvm-5.0.1.src.tar.xz
Source99 : http://releases.llvm.org/5.0.1/llvm-5.0.1.src.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause MIT NCSA
Requires: compat-llvm-soname5-bin
Requires: compat-llvm-soname5-lib
Requires: compat-llvm-soname5-data
BuildRequires : cmake
BuildRequires : go
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
See docs/CMake.html for instructions on how to build LLVM with CMake.

%package bin
Summary: bin components for the compat-llvm-soname5 package.
Group: Binaries
Requires: compat-llvm-soname5-data

%description bin
bin components for the compat-llvm-soname5 package.


%package data
Summary: data components for the compat-llvm-soname5 package.
Group: Data

%description data
data components for the compat-llvm-soname5 package.


%package dev
Summary: dev components for the compat-llvm-soname5 package.
Group: Development
Requires: compat-llvm-soname5-lib
Requires: compat-llvm-soname5-bin
Requires: compat-llvm-soname5-data
Provides: compat-llvm-soname5-devel

%description dev
dev components for the compat-llvm-soname5 package.


%package lib
Summary: lib components for the compat-llvm-soname5 package.
Group: Libraries
Requires: compat-llvm-soname5-data

%description lib
lib components for the compat-llvm-soname5 package.


%prep
%setup -q -n llvm-5.0.1.src

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1521073443
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1521073443
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/bugpoint
%exclude /usr/bin/llc
%exclude /usr/bin/lli
%exclude /usr/bin/llvm-ar
%exclude /usr/bin/llvm-as
%exclude /usr/bin/llvm-bcanalyzer
%exclude /usr/bin/llvm-c-test
%exclude /usr/bin/llvm-cat
%exclude /usr/bin/llvm-config
%exclude /usr/bin/llvm-cov
%exclude /usr/bin/llvm-cvtres
%exclude /usr/bin/llvm-cxxdump
%exclude /usr/bin/llvm-cxxfilt
%exclude /usr/bin/llvm-diff
%exclude /usr/bin/llvm-dis
%exclude /usr/bin/llvm-dlltool
%exclude /usr/bin/llvm-dsymutil
%exclude /usr/bin/llvm-dwarfdump
%exclude /usr/bin/llvm-dwp
%exclude /usr/bin/llvm-extract
%exclude /usr/bin/llvm-lib
%exclude /usr/bin/llvm-link
%exclude /usr/bin/llvm-lto
%exclude /usr/bin/llvm-lto2
%exclude /usr/bin/llvm-mc
%exclude /usr/bin/llvm-mcmarkup
%exclude /usr/bin/llvm-modextract
%exclude /usr/bin/llvm-mt
%exclude /usr/bin/llvm-nm
%exclude /usr/bin/llvm-objdump
%exclude /usr/bin/llvm-opt-report
%exclude /usr/bin/llvm-pdbutil
%exclude /usr/bin/llvm-profdata
%exclude /usr/bin/llvm-ranlib
%exclude /usr/bin/llvm-readelf
%exclude /usr/bin/llvm-readobj
%exclude /usr/bin/llvm-rtdyld
%exclude /usr/bin/llvm-size
%exclude /usr/bin/llvm-split
%exclude /usr/bin/llvm-stress
%exclude /usr/bin/llvm-strings
%exclude /usr/bin/llvm-symbolizer
%exclude /usr/bin/llvm-tblgen
%exclude /usr/bin/llvm-xray
%exclude /usr/bin/obj2yaml
%exclude /usr/bin/opt
%exclude /usr/bin/sancov
%exclude /usr/bin/sanstats
%exclude /usr/bin/verify-uselistorder
%exclude /usr/bin/yaml2obj

%files data
%defattr(-,root,root,-)
%exclude /usr/share/opt-viewer/__pycache__/opt-diff.cpython-36.pyc
%exclude /usr/share/opt-viewer/__pycache__/opt-stats.cpython-36.pyc
%exclude /usr/share/opt-viewer/__pycache__/opt-viewer.cpython-36.pyc
%exclude /usr/share/opt-viewer/__pycache__/optpmap.cpython-36.pyc
%exclude /usr/share/opt-viewer/__pycache__/optrecord.cpython-36.pyc
%exclude /usr/share/opt-viewer/opt-diff.py
%exclude /usr/share/opt-viewer/opt-stats.py
%exclude /usr/share/opt-viewer/opt-viewer.py
%exclude /usr/share/opt-viewer/optpmap.py
%exclude /usr/share/opt-viewer/optrecord.py
%exclude /usr/share/opt-viewer/style.css

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/llvm-c/Analysis.h
%exclude /usr/include/llvm-c/BitReader.h
%exclude /usr/include/llvm-c/BitWriter.h
%exclude /usr/include/llvm-c/Core.h
%exclude /usr/include/llvm-c/Disassembler.h
%exclude /usr/include/llvm-c/ErrorHandling.h
%exclude /usr/include/llvm-c/ExecutionEngine.h
%exclude /usr/include/llvm-c/IRReader.h
%exclude /usr/include/llvm-c/Initialization.h
%exclude /usr/include/llvm-c/LinkTimeOptimizer.h
%exclude /usr/include/llvm-c/Linker.h
%exclude /usr/include/llvm-c/Object.h
%exclude /usr/include/llvm-c/OrcBindings.h
%exclude /usr/include/llvm-c/Support.h
%exclude /usr/include/llvm-c/Target.h
%exclude /usr/include/llvm-c/TargetMachine.h
%exclude /usr/include/llvm-c/Transforms/IPO.h
%exclude /usr/include/llvm-c/Transforms/PassManagerBuilder.h
%exclude /usr/include/llvm-c/Transforms/Scalar.h
%exclude /usr/include/llvm-c/Transforms/Vectorize.h
%exclude /usr/include/llvm-c/Types.h
%exclude /usr/include/llvm-c/lto.h
%exclude /usr/include/llvm/ADT/APFloat.h
%exclude /usr/include/llvm/ADT/APInt.h
%exclude /usr/include/llvm/ADT/APSInt.h
%exclude /usr/include/llvm/ADT/AllocatorList.h
%exclude /usr/include/llvm/ADT/ArrayRef.h
%exclude /usr/include/llvm/ADT/BitVector.h
%exclude /usr/include/llvm/ADT/BitmaskEnum.h
%exclude /usr/include/llvm/ADT/BreadthFirstIterator.h
%exclude /usr/include/llvm/ADT/CachedHashString.h
%exclude /usr/include/llvm/ADT/DAGDeltaAlgorithm.h
%exclude /usr/include/llvm/ADT/DeltaAlgorithm.h
%exclude /usr/include/llvm/ADT/DenseMap.h
%exclude /usr/include/llvm/ADT/DenseMapInfo.h
%exclude /usr/include/llvm/ADT/DenseSet.h
%exclude /usr/include/llvm/ADT/DepthFirstIterator.h
%exclude /usr/include/llvm/ADT/EpochTracker.h
%exclude /usr/include/llvm/ADT/EquivalenceClasses.h
%exclude /usr/include/llvm/ADT/FoldingSet.h
%exclude /usr/include/llvm/ADT/GraphTraits.h
%exclude /usr/include/llvm/ADT/Hashing.h
%exclude /usr/include/llvm/ADT/ImmutableList.h
%exclude /usr/include/llvm/ADT/ImmutableMap.h
%exclude /usr/include/llvm/ADT/ImmutableSet.h
%exclude /usr/include/llvm/ADT/IndexedMap.h
%exclude /usr/include/llvm/ADT/IntEqClasses.h
%exclude /usr/include/llvm/ADT/IntervalMap.h
%exclude /usr/include/llvm/ADT/IntrusiveRefCntPtr.h
%exclude /usr/include/llvm/ADT/MapVector.h
%exclude /usr/include/llvm/ADT/None.h
%exclude /usr/include/llvm/ADT/Optional.h
%exclude /usr/include/llvm/ADT/PackedVector.h
%exclude /usr/include/llvm/ADT/PointerEmbeddedInt.h
%exclude /usr/include/llvm/ADT/PointerIntPair.h
%exclude /usr/include/llvm/ADT/PointerSumType.h
%exclude /usr/include/llvm/ADT/PointerUnion.h
%exclude /usr/include/llvm/ADT/PostOrderIterator.h
%exclude /usr/include/llvm/ADT/PriorityQueue.h
%exclude /usr/include/llvm/ADT/PriorityWorklist.h
%exclude /usr/include/llvm/ADT/SCCIterator.h
%exclude /usr/include/llvm/ADT/STLExtras.h
%exclude /usr/include/llvm/ADT/ScopeExit.h
%exclude /usr/include/llvm/ADT/ScopedHashTable.h
%exclude /usr/include/llvm/ADT/Sequence.h
%exclude /usr/include/llvm/ADT/SetOperations.h
%exclude /usr/include/llvm/ADT/SetVector.h
%exclude /usr/include/llvm/ADT/SmallBitVector.h
%exclude /usr/include/llvm/ADT/SmallPtrSet.h
%exclude /usr/include/llvm/ADT/SmallSet.h
%exclude /usr/include/llvm/ADT/SmallString.h
%exclude /usr/include/llvm/ADT/SmallVector.h
%exclude /usr/include/llvm/ADT/SparseBitVector.h
%exclude /usr/include/llvm/ADT/SparseMultiSet.h
%exclude /usr/include/llvm/ADT/SparseSet.h
%exclude /usr/include/llvm/ADT/Statistic.h
%exclude /usr/include/llvm/ADT/StringExtras.h
%exclude /usr/include/llvm/ADT/StringMap.h
%exclude /usr/include/llvm/ADT/StringRef.h
%exclude /usr/include/llvm/ADT/StringSet.h
%exclude /usr/include/llvm/ADT/StringSwitch.h
%exclude /usr/include/llvm/ADT/TinyPtrVector.h
%exclude /usr/include/llvm/ADT/Triple.h
%exclude /usr/include/llvm/ADT/Twine.h
%exclude /usr/include/llvm/ADT/UniqueVector.h
%exclude /usr/include/llvm/ADT/VariadicFunction.h
%exclude /usr/include/llvm/ADT/edit_distance.h
%exclude /usr/include/llvm/ADT/ilist.h
%exclude /usr/include/llvm/ADT/ilist_base.h
%exclude /usr/include/llvm/ADT/ilist_iterator.h
%exclude /usr/include/llvm/ADT/ilist_node.h
%exclude /usr/include/llvm/ADT/ilist_node_base.h
%exclude /usr/include/llvm/ADT/ilist_node_options.h
%exclude /usr/include/llvm/ADT/iterator.h
%exclude /usr/include/llvm/ADT/iterator_range.h
%exclude /usr/include/llvm/ADT/simple_ilist.h
%exclude /usr/include/llvm/Analysis/AliasAnalysis.h
%exclude /usr/include/llvm/Analysis/AliasAnalysisEvaluator.h
%exclude /usr/include/llvm/Analysis/AliasSetTracker.h
%exclude /usr/include/llvm/Analysis/AssumptionCache.h
%exclude /usr/include/llvm/Analysis/BasicAliasAnalysis.h
%exclude /usr/include/llvm/Analysis/BlockFrequencyInfo.h
%exclude /usr/include/llvm/Analysis/BlockFrequencyInfoImpl.h
%exclude /usr/include/llvm/Analysis/BranchProbabilityInfo.h
%exclude /usr/include/llvm/Analysis/CFG.h
%exclude /usr/include/llvm/Analysis/CFGPrinter.h
%exclude /usr/include/llvm/Analysis/CFLAliasAnalysisUtils.h
%exclude /usr/include/llvm/Analysis/CFLAndersAliasAnalysis.h
%exclude /usr/include/llvm/Analysis/CFLSteensAliasAnalysis.h
%exclude /usr/include/llvm/Analysis/CGSCCPassManager.h
%exclude /usr/include/llvm/Analysis/CallGraph.h
%exclude /usr/include/llvm/Analysis/CallGraphSCCPass.h
%exclude /usr/include/llvm/Analysis/CallPrinter.h
%exclude /usr/include/llvm/Analysis/CaptureTracking.h
%exclude /usr/include/llvm/Analysis/CodeMetrics.h
%exclude /usr/include/llvm/Analysis/ConstantFolding.h
%exclude /usr/include/llvm/Analysis/DOTGraphTraitsPass.h
%exclude /usr/include/llvm/Analysis/DemandedBits.h
%exclude /usr/include/llvm/Analysis/DependenceAnalysis.h
%exclude /usr/include/llvm/Analysis/DivergenceAnalysis.h
%exclude /usr/include/llvm/Analysis/DomPrinter.h
%exclude /usr/include/llvm/Analysis/DominanceFrontier.h
%exclude /usr/include/llvm/Analysis/DominanceFrontierImpl.h
%exclude /usr/include/llvm/Analysis/EHPersonalities.h
%exclude /usr/include/llvm/Analysis/GlobalsModRef.h
%exclude /usr/include/llvm/Analysis/IVUsers.h
%exclude /usr/include/llvm/Analysis/IndirectCallPromotionAnalysis.h
%exclude /usr/include/llvm/Analysis/IndirectCallSiteVisitor.h
%exclude /usr/include/llvm/Analysis/InlineCost.h
%exclude /usr/include/llvm/Analysis/InstructionSimplify.h
%exclude /usr/include/llvm/Analysis/Interval.h
%exclude /usr/include/llvm/Analysis/IntervalIterator.h
%exclude /usr/include/llvm/Analysis/IntervalPartition.h
%exclude /usr/include/llvm/Analysis/IteratedDominanceFrontier.h
%exclude /usr/include/llvm/Analysis/LazyBlockFrequencyInfo.h
%exclude /usr/include/llvm/Analysis/LazyBranchProbabilityInfo.h
%exclude /usr/include/llvm/Analysis/LazyCallGraph.h
%exclude /usr/include/llvm/Analysis/LazyValueInfo.h
%exclude /usr/include/llvm/Analysis/Lint.h
%exclude /usr/include/llvm/Analysis/Loads.h
%exclude /usr/include/llvm/Analysis/LoopAccessAnalysis.h
%exclude /usr/include/llvm/Analysis/LoopAnalysisManager.h
%exclude /usr/include/llvm/Analysis/LoopInfo.h
%exclude /usr/include/llvm/Analysis/LoopInfoImpl.h
%exclude /usr/include/llvm/Analysis/LoopIterator.h
%exclude /usr/include/llvm/Analysis/LoopPass.h
%exclude /usr/include/llvm/Analysis/LoopUnrollAnalyzer.h
%exclude /usr/include/llvm/Analysis/MemoryBuiltins.h
%exclude /usr/include/llvm/Analysis/MemoryDependenceAnalysis.h
%exclude /usr/include/llvm/Analysis/MemoryLocation.h
%exclude /usr/include/llvm/Analysis/MemorySSA.h
%exclude /usr/include/llvm/Analysis/MemorySSAUpdater.h
%exclude /usr/include/llvm/Analysis/ModuleSummaryAnalysis.h
%exclude /usr/include/llvm/Analysis/ObjCARCAliasAnalysis.h
%exclude /usr/include/llvm/Analysis/ObjCARCAnalysisUtils.h
%exclude /usr/include/llvm/Analysis/ObjCARCInstKind.h
%exclude /usr/include/llvm/Analysis/ObjectUtils.h
%exclude /usr/include/llvm/Analysis/OptimizationDiagnosticInfo.h
%exclude /usr/include/llvm/Analysis/OrderedBasicBlock.h
%exclude /usr/include/llvm/Analysis/PHITransAddr.h
%exclude /usr/include/llvm/Analysis/Passes.h
%exclude /usr/include/llvm/Analysis/PostDominators.h
%exclude /usr/include/llvm/Analysis/ProfileSummaryInfo.h
%exclude /usr/include/llvm/Analysis/PtrUseVisitor.h
%exclude /usr/include/llvm/Analysis/RegionInfo.h
%exclude /usr/include/llvm/Analysis/RegionInfoImpl.h
%exclude /usr/include/llvm/Analysis/RegionIterator.h
%exclude /usr/include/llvm/Analysis/RegionPass.h
%exclude /usr/include/llvm/Analysis/RegionPrinter.h
%exclude /usr/include/llvm/Analysis/ScalarEvolution.h
%exclude /usr/include/llvm/Analysis/ScalarEvolutionAliasAnalysis.h
%exclude /usr/include/llvm/Analysis/ScalarEvolutionExpander.h
%exclude /usr/include/llvm/Analysis/ScalarEvolutionExpressions.h
%exclude /usr/include/llvm/Analysis/ScalarEvolutionNormalization.h
%exclude /usr/include/llvm/Analysis/ScopedNoAliasAA.h
%exclude /usr/include/llvm/Analysis/SparsePropagation.h
%exclude /usr/include/llvm/Analysis/TargetFolder.h
%exclude /usr/include/llvm/Analysis/TargetLibraryInfo.def
%exclude /usr/include/llvm/Analysis/TargetLibraryInfo.h
%exclude /usr/include/llvm/Analysis/TargetTransformInfo.h
%exclude /usr/include/llvm/Analysis/TargetTransformInfoImpl.h
%exclude /usr/include/llvm/Analysis/Trace.h
%exclude /usr/include/llvm/Analysis/TypeBasedAliasAnalysis.h
%exclude /usr/include/llvm/Analysis/TypeMetadataUtils.h
%exclude /usr/include/llvm/Analysis/ValueTracking.h
%exclude /usr/include/llvm/Analysis/VectorUtils.h
%exclude /usr/include/llvm/AsmParser/Parser.h
%exclude /usr/include/llvm/AsmParser/SlotMapping.h
%exclude /usr/include/llvm/BinaryFormat/COFF.h
%exclude /usr/include/llvm/BinaryFormat/Dwarf.def
%exclude /usr/include/llvm/BinaryFormat/Dwarf.h
%exclude /usr/include/llvm/BinaryFormat/ELF.h
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/AArch64.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/AMDGPU.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/ARM.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/AVR.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/BPF.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/Hexagon.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/Lanai.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/Mips.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/PowerPC.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/PowerPC64.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/RISCV.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/Sparc.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/SystemZ.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/WebAssembly.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/i386.def
%exclude /usr/include/llvm/BinaryFormat/ELFRelocs/x86_64.def
%exclude /usr/include/llvm/BinaryFormat/MachO.def
%exclude /usr/include/llvm/BinaryFormat/MachO.h
%exclude /usr/include/llvm/BinaryFormat/Magic.h
%exclude /usr/include/llvm/BinaryFormat/Wasm.h
%exclude /usr/include/llvm/BinaryFormat/WasmRelocs/WebAssembly.def
%exclude /usr/include/llvm/Bitcode/BitCodes.h
%exclude /usr/include/llvm/Bitcode/BitcodeReader.h
%exclude /usr/include/llvm/Bitcode/BitcodeWriter.h
%exclude /usr/include/llvm/Bitcode/BitcodeWriterPass.h
%exclude /usr/include/llvm/Bitcode/BitstreamReader.h
%exclude /usr/include/llvm/Bitcode/BitstreamWriter.h
%exclude /usr/include/llvm/Bitcode/LLVMBitCodes.h
%exclude /usr/include/llvm/CodeGen/Analysis.h
%exclude /usr/include/llvm/CodeGen/AsmPrinter.h
%exclude /usr/include/llvm/CodeGen/AtomicExpandUtils.h
%exclude /usr/include/llvm/CodeGen/BasicTTIImpl.h
%exclude /usr/include/llvm/CodeGen/CalcSpillWeights.h
%exclude /usr/include/llvm/CodeGen/CallingConvLower.h
%exclude /usr/include/llvm/CodeGen/CommandFlags.h
%exclude /usr/include/llvm/CodeGen/DAGCombine.h
%exclude /usr/include/llvm/CodeGen/DFAPacketizer.h
%exclude /usr/include/llvm/CodeGen/DIE.h
%exclude /usr/include/llvm/CodeGen/DIEValue.def
%exclude /usr/include/llvm/CodeGen/DwarfStringPoolEntry.h
%exclude /usr/include/llvm/CodeGen/EdgeBundles.h
%exclude /usr/include/llvm/CodeGen/ExecutionDepsFix.h
%exclude /usr/include/llvm/CodeGen/ExpandReductions.h
%exclude /usr/include/llvm/CodeGen/FastISel.h
%exclude /usr/include/llvm/CodeGen/FaultMaps.h
%exclude /usr/include/llvm/CodeGen/FunctionLoweringInfo.h
%exclude /usr/include/llvm/CodeGen/GCMetadata.h
%exclude /usr/include/llvm/CodeGen/GCMetadataPrinter.h
%exclude /usr/include/llvm/CodeGen/GCStrategy.h
%exclude /usr/include/llvm/CodeGen/GCs.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/CallLowering.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/GISelAccessor.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/IRTranslator.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/InstructionSelect.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/InstructionSelector.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/InstructionSelectorImpl.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/Legalizer.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/LegalizerHelper.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/Localizer.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/RegBankSelect.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/RegisterBank.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/RegisterBankInfo.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/Types.h
%exclude /usr/include/llvm/CodeGen/GlobalISel/Utils.h
%exclude /usr/include/llvm/CodeGen/ISDOpcodes.h
%exclude /usr/include/llvm/CodeGen/IntrinsicLowering.h
%exclude /usr/include/llvm/CodeGen/LatencyPriorityQueue.h
%exclude /usr/include/llvm/CodeGen/LazyMachineBlockFrequencyInfo.h
%exclude /usr/include/llvm/CodeGen/LexicalScopes.h
%exclude /usr/include/llvm/CodeGen/LinkAllAsmWriterComponents.h
%exclude /usr/include/llvm/CodeGen/LinkAllCodegenComponents.h
%exclude /usr/include/llvm/CodeGen/LiveInterval.h
%exclude /usr/include/llvm/CodeGen/LiveIntervalAnalysis.h
%exclude /usr/include/llvm/CodeGen/LiveIntervalUnion.h
%exclude /usr/include/llvm/CodeGen/LivePhysRegs.h
%exclude /usr/include/llvm/CodeGen/LiveRangeEdit.h
%exclude /usr/include/llvm/CodeGen/LiveRegMatrix.h
%exclude /usr/include/llvm/CodeGen/LiveRegUnits.h
%exclude /usr/include/llvm/CodeGen/LiveStackAnalysis.h
%exclude /usr/include/llvm/CodeGen/LiveVariables.h
%exclude /usr/include/llvm/CodeGen/LowLevelType.h
%exclude /usr/include/llvm/CodeGen/MIRParser/MIRParser.h
%exclude /usr/include/llvm/CodeGen/MIRPrinter.h
%exclude /usr/include/llvm/CodeGen/MIRYamlMapping.h
%exclude /usr/include/llvm/CodeGen/MachORelocation.h
%exclude /usr/include/llvm/CodeGen/MachineBasicBlock.h
%exclude /usr/include/llvm/CodeGen/MachineBlockFrequencyInfo.h
%exclude /usr/include/llvm/CodeGen/MachineBranchProbabilityInfo.h
%exclude /usr/include/llvm/CodeGen/MachineCombinerPattern.h
%exclude /usr/include/llvm/CodeGen/MachineConstantPool.h
%exclude /usr/include/llvm/CodeGen/MachineDominanceFrontier.h
%exclude /usr/include/llvm/CodeGen/MachineDominators.h
%exclude /usr/include/llvm/CodeGen/MachineFrameInfo.h
%exclude /usr/include/llvm/CodeGen/MachineFunction.h
%exclude /usr/include/llvm/CodeGen/MachineFunctionPass.h
%exclude /usr/include/llvm/CodeGen/MachineInstr.h
%exclude /usr/include/llvm/CodeGen/MachineInstrBuilder.h
%exclude /usr/include/llvm/CodeGen/MachineInstrBundle.h
%exclude /usr/include/llvm/CodeGen/MachineInstrBundleIterator.h
%exclude /usr/include/llvm/CodeGen/MachineJumpTableInfo.h
%exclude /usr/include/llvm/CodeGen/MachineLoopInfo.h
%exclude /usr/include/llvm/CodeGen/MachineMemOperand.h
%exclude /usr/include/llvm/CodeGen/MachineModuleInfo.h
%exclude /usr/include/llvm/CodeGen/MachineModuleInfoImpls.h
%exclude /usr/include/llvm/CodeGen/MachineOperand.h
%exclude /usr/include/llvm/CodeGen/MachineOptimizationRemarkEmitter.h
%exclude /usr/include/llvm/CodeGen/MachinePassRegistry.h
%exclude /usr/include/llvm/CodeGen/MachinePostDominators.h
%exclude /usr/include/llvm/CodeGen/MachineRegionInfo.h
%exclude /usr/include/llvm/CodeGen/MachineRegisterInfo.h
%exclude /usr/include/llvm/CodeGen/MachineSSAUpdater.h
%exclude /usr/include/llvm/CodeGen/MachineScheduler.h
%exclude /usr/include/llvm/CodeGen/MachineTraceMetrics.h
%exclude /usr/include/llvm/CodeGen/MachineValueType.h
%exclude /usr/include/llvm/CodeGen/MacroFusion.h
%exclude /usr/include/llvm/CodeGen/PBQP/CostAllocator.h
%exclude /usr/include/llvm/CodeGen/PBQP/Graph.h
%exclude /usr/include/llvm/CodeGen/PBQP/Math.h
%exclude /usr/include/llvm/CodeGen/PBQP/ReductionRules.h
%exclude /usr/include/llvm/CodeGen/PBQP/Solution.h
%exclude /usr/include/llvm/CodeGen/PBQPRAConstraint.h
%exclude /usr/include/llvm/CodeGen/ParallelCG.h
%exclude /usr/include/llvm/CodeGen/Passes.h
%exclude /usr/include/llvm/CodeGen/PreISelIntrinsicLowering.h
%exclude /usr/include/llvm/CodeGen/PseudoSourceValue.h
%exclude /usr/include/llvm/CodeGen/RegAllocPBQP.h
%exclude /usr/include/llvm/CodeGen/RegAllocRegistry.h
%exclude /usr/include/llvm/CodeGen/RegisterClassInfo.h
%exclude /usr/include/llvm/CodeGen/RegisterPressure.h
%exclude /usr/include/llvm/CodeGen/RegisterScavenging.h
%exclude /usr/include/llvm/CodeGen/RegisterUsageInfo.h
%exclude /usr/include/llvm/CodeGen/ResourcePriorityQueue.h
%exclude /usr/include/llvm/CodeGen/RuntimeLibcalls.h
%exclude /usr/include/llvm/CodeGen/ScheduleDAG.h
%exclude /usr/include/llvm/CodeGen/ScheduleDAGInstrs.h
%exclude /usr/include/llvm/CodeGen/ScheduleDAGMutation.h
%exclude /usr/include/llvm/CodeGen/ScheduleDFS.h
%exclude /usr/include/llvm/CodeGen/ScheduleHazardRecognizer.h
%exclude /usr/include/llvm/CodeGen/SchedulerRegistry.h
%exclude /usr/include/llvm/CodeGen/ScoreboardHazardRecognizer.h
%exclude /usr/include/llvm/CodeGen/SelectionDAG.h
%exclude /usr/include/llvm/CodeGen/SelectionDAGAddressAnalysis.h
%exclude /usr/include/llvm/CodeGen/SelectionDAGISel.h
%exclude /usr/include/llvm/CodeGen/SelectionDAGNodes.h
%exclude /usr/include/llvm/CodeGen/SelectionDAGTargetInfo.h
%exclude /usr/include/llvm/CodeGen/SlotIndexes.h
%exclude /usr/include/llvm/CodeGen/StackMaps.h
%exclude /usr/include/llvm/CodeGen/StackProtector.h
%exclude /usr/include/llvm/CodeGen/TailDuplicator.h
%exclude /usr/include/llvm/CodeGen/TargetLoweringObjectFileImpl.h
%exclude /usr/include/llvm/CodeGen/TargetPassConfig.h
%exclude /usr/include/llvm/CodeGen/TargetSchedule.h
%exclude /usr/include/llvm/CodeGen/UnreachableBlockElim.h
%exclude /usr/include/llvm/CodeGen/ValueTypes.h
%exclude /usr/include/llvm/CodeGen/ValueTypes.td
%exclude /usr/include/llvm/CodeGen/VirtRegMap.h
%exclude /usr/include/llvm/CodeGen/WinEHFuncInfo.h
%exclude /usr/include/llvm/Config/AsmParsers.def
%exclude /usr/include/llvm/Config/AsmPrinters.def
%exclude /usr/include/llvm/Config/Disassemblers.def
%exclude /usr/include/llvm/Config/Targets.def
%exclude /usr/include/llvm/Config/abi-breaking.h
%exclude /usr/include/llvm/Config/llvm-config.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CVDebugRecord.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CVRecord.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CVSymbolVisitor.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CVTypeVisitor.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CodeView.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CodeViewError.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CodeViewRecordIO.h
%exclude /usr/include/llvm/DebugInfo/CodeView/CodeViewSymbols.def
%exclude /usr/include/llvm/DebugInfo/CodeView/CodeViewTypes.def
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugChecksumsSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugCrossExSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugCrossImpSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugFrameDataSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugLinesSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugStringTableSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugSubsectionRecord.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugSubsectionVisitor.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugSymbolRVASubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugSymbolsSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/DebugUnknownSubsection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/EnumTables.h
%exclude /usr/include/llvm/DebugInfo/CodeView/Formatters.h
%exclude /usr/include/llvm/DebugInfo/CodeView/FunctionId.h
%exclude /usr/include/llvm/DebugInfo/CodeView/GUID.h
%exclude /usr/include/llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/Line.h
%exclude /usr/include/llvm/DebugInfo/CodeView/RecordSerialization.h
%exclude /usr/include/llvm/DebugInfo/CodeView/StringsAndChecksums.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolDeserializer.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolDumpDelegate.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolDumper.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolRecord.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolRecordMapping.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolSerializer.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolVisitorCallbackPipeline.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolVisitorCallbacks.h
%exclude /usr/include/llvm/DebugInfo/CodeView/SymbolVisitorDelegate.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeCollection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeDeserializer.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeDumpVisitor.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeIndex.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeIndexDiscovery.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeName.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeRecord.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeRecordBuilder.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeRecordMapping.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeSerializer.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeStreamMerger.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeSymbolEmitter.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeTableBuilder.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeTableCollection.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeVisitorCallbackPipeline.h
%exclude /usr/include/llvm/DebugInfo/CodeView/TypeVisitorCallbacks.h
%exclude /usr/include/llvm/DebugInfo/DIContext.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFAttribute.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFCompileUnit.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFContext.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDataExtractor.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugArangeSet.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugAranges.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugFrame.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugLine.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugLoc.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugMacro.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugPubTable.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDebugRangeList.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFDie.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFFormValue.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFGdbIndex.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFRelocMap.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFSection.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFTypeUnit.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFUnit.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFUnitIndex.h
%exclude /usr/include/llvm/DebugInfo/DWARF/DWARFVerifier.h
%exclude /usr/include/llvm/DebugInfo/MSF/IMSFFile.h
%exclude /usr/include/llvm/DebugInfo/MSF/MSFBuilder.h
%exclude /usr/include/llvm/DebugInfo/MSF/MSFCommon.h
%exclude /usr/include/llvm/DebugInfo/MSF/MSFError.h
%exclude /usr/include/llvm/DebugInfo/MSF/MSFStreamLayout.h
%exclude /usr/include/llvm/DebugInfo/MSF/MappedBlockStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/ConcreteSymbolEnumerator.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIADataStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIAEnumDebugStreams.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIAEnumLineNumbers.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIAEnumSourceFiles.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIAEnumSymbols.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIAError.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIALineNumber.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIARawSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIASession.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIASourceFile.h
%exclude /usr/include/llvm/DebugInfo/PDB/DIA/DIASupport.h
%exclude /usr/include/llvm/DebugInfo/PDB/GenericError.h
%exclude /usr/include/llvm/DebugInfo/PDB/IPDBDataStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/IPDBEnumChildren.h
%exclude /usr/include/llvm/DebugInfo/PDB/IPDBLineNumber.h
%exclude /usr/include/llvm/DebugInfo/PDB/IPDBRawSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/IPDBSession.h
%exclude /usr/include/llvm/DebugInfo/PDB/IPDBSourceFile.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/DbiModuleDescriptor.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/DbiModuleDescriptorBuilder.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/DbiModuleList.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/DbiStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/DbiStreamBuilder.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/EnumTables.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/Formatters.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/GlobalsStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/Hash.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/HashTable.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/ISectionContribVisitor.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/InfoStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/InfoStreamBuilder.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/ModuleDebugStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/NamedStreamMap.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/NativeBuiltinSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/NativeCompilandSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/NativeEnumModules.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/NativeExeSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/NativeRawSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/NativeSession.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/PDBFile.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/PDBFileBuilder.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/PDBStringTable.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/PDBStringTableBuilder.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/PublicsStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/PublicsStreamBuilder.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/RawConstants.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/RawError.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/RawTypes.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/SymbolStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/TpiHashing.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/TpiStream.h
%exclude /usr/include/llvm/DebugInfo/PDB/Native/TpiStreamBuilder.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDB.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBContext.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBExtras.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymDumper.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolAnnotation.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolBlock.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolCompiland.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolCompilandDetails.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolCompilandEnv.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolCustom.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolData.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolExe.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolFunc.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolFuncDebugEnd.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolFuncDebugStart.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolLabel.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolPublicSymbol.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolThunk.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeArray.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeBaseClass.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeBuiltin.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeCustom.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeDimension.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeEnum.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeFriend.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeFunctionArg.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeFunctionSig.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeManaged.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypePointer.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeTypedef.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeUDT.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeVTable.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolTypeVTableShape.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolUnknown.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBSymbolUsingNamespace.h
%exclude /usr/include/llvm/DebugInfo/PDB/PDBTypes.h
%exclude /usr/include/llvm/DebugInfo/PDB/UDTLayout.h
%exclude /usr/include/llvm/DebugInfo/Symbolize/DIPrinter.h
%exclude /usr/include/llvm/DebugInfo/Symbolize/SymbolizableModule.h
%exclude /usr/include/llvm/DebugInfo/Symbolize/Symbolize.h
%exclude /usr/include/llvm/Demangle/Demangle.h
%exclude /usr/include/llvm/ExecutionEngine/ExecutionEngine.h
%exclude /usr/include/llvm/ExecutionEngine/GenericValue.h
%exclude /usr/include/llvm/ExecutionEngine/Interpreter.h
%exclude /usr/include/llvm/ExecutionEngine/JITEventListener.h
%exclude /usr/include/llvm/ExecutionEngine/JITSymbol.h
%exclude /usr/include/llvm/ExecutionEngine/MCJIT.h
%exclude /usr/include/llvm/ExecutionEngine/OProfileWrapper.h
%exclude /usr/include/llvm/ExecutionEngine/ObjectCache.h
%exclude /usr/include/llvm/ExecutionEngine/ObjectMemoryBuffer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/CompileUtils.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/GlobalMappingLayer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/IRTransformLayer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/IndirectionUtils.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/LambdaResolver.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/LazyEmittingLayer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/NullResolver.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/ObjectTransformLayer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/OrcABISupport.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/OrcError.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetRPCAPI.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetServer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/RPCSerialization.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/RPCUtils.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h
%exclude /usr/include/llvm/ExecutionEngine/Orc/RawByteChannel.h
%exclude /usr/include/llvm/ExecutionEngine/OrcMCJITReplacement.h
%exclude /usr/include/llvm/ExecutionEngine/RTDyldMemoryManager.h
%exclude /usr/include/llvm/ExecutionEngine/RuntimeDyld.h
%exclude /usr/include/llvm/ExecutionEngine/RuntimeDyldChecker.h
%exclude /usr/include/llvm/ExecutionEngine/SectionMemoryManager.h
%exclude /usr/include/llvm/IR/Argument.h
%exclude /usr/include/llvm/IR/AssemblyAnnotationWriter.h
%exclude /usr/include/llvm/IR/Attributes.gen
%exclude /usr/include/llvm/IR/Attributes.h
%exclude /usr/include/llvm/IR/Attributes.td
%exclude /usr/include/llvm/IR/AutoUpgrade.h
%exclude /usr/include/llvm/IR/BasicBlock.h
%exclude /usr/include/llvm/IR/CFG.h
%exclude /usr/include/llvm/IR/CallSite.h
%exclude /usr/include/llvm/IR/CallingConv.h
%exclude /usr/include/llvm/IR/Comdat.h
%exclude /usr/include/llvm/IR/Constant.h
%exclude /usr/include/llvm/IR/ConstantFolder.h
%exclude /usr/include/llvm/IR/ConstantRange.h
%exclude /usr/include/llvm/IR/Constants.h
%exclude /usr/include/llvm/IR/DIBuilder.h
%exclude /usr/include/llvm/IR/DataLayout.h
%exclude /usr/include/llvm/IR/DebugInfo.h
%exclude /usr/include/llvm/IR/DebugInfoFlags.def
%exclude /usr/include/llvm/IR/DebugInfoMetadata.h
%exclude /usr/include/llvm/IR/DebugLoc.h
%exclude /usr/include/llvm/IR/DerivedTypes.h
%exclude /usr/include/llvm/IR/DerivedUser.h
%exclude /usr/include/llvm/IR/DiagnosticInfo.h
%exclude /usr/include/llvm/IR/DiagnosticPrinter.h
%exclude /usr/include/llvm/IR/Dominators.h
%exclude /usr/include/llvm/IR/Function.h
%exclude /usr/include/llvm/IR/GVMaterializer.h
%exclude /usr/include/llvm/IR/GetElementPtrTypeIterator.h
%exclude /usr/include/llvm/IR/GlobalAlias.h
%exclude /usr/include/llvm/IR/GlobalIFunc.h
%exclude /usr/include/llvm/IR/GlobalIndirectSymbol.h
%exclude /usr/include/llvm/IR/GlobalObject.h
%exclude /usr/include/llvm/IR/GlobalValue.h
%exclude /usr/include/llvm/IR/GlobalVariable.h
%exclude /usr/include/llvm/IR/IRBuilder.h
%exclude /usr/include/llvm/IR/IRPrintingPasses.h
%exclude /usr/include/llvm/IR/InlineAsm.h
%exclude /usr/include/llvm/IR/InstIterator.h
%exclude /usr/include/llvm/IR/InstVisitor.h
%exclude /usr/include/llvm/IR/InstrTypes.h
%exclude /usr/include/llvm/IR/Instruction.def
%exclude /usr/include/llvm/IR/Instruction.h
%exclude /usr/include/llvm/IR/Instructions.h
%exclude /usr/include/llvm/IR/IntrinsicInst.h
%exclude /usr/include/llvm/IR/Intrinsics.gen
%exclude /usr/include/llvm/IR/Intrinsics.h
%exclude /usr/include/llvm/IR/Intrinsics.td
%exclude /usr/include/llvm/IR/IntrinsicsAArch64.td
%exclude /usr/include/llvm/IR/IntrinsicsAMDGPU.td
%exclude /usr/include/llvm/IR/IntrinsicsARM.td
%exclude /usr/include/llvm/IR/IntrinsicsBPF.td
%exclude /usr/include/llvm/IR/IntrinsicsHexagon.td
%exclude /usr/include/llvm/IR/IntrinsicsMips.td
%exclude /usr/include/llvm/IR/IntrinsicsNVVM.td
%exclude /usr/include/llvm/IR/IntrinsicsPowerPC.td
%exclude /usr/include/llvm/IR/IntrinsicsSystemZ.td
%exclude /usr/include/llvm/IR/IntrinsicsWebAssembly.td
%exclude /usr/include/llvm/IR/IntrinsicsX86.td
%exclude /usr/include/llvm/IR/IntrinsicsXCore.td
%exclude /usr/include/llvm/IR/LLVMContext.h
%exclude /usr/include/llvm/IR/LegacyPassManager.h
%exclude /usr/include/llvm/IR/LegacyPassManagers.h
%exclude /usr/include/llvm/IR/LegacyPassNameParser.h
%exclude /usr/include/llvm/IR/MDBuilder.h
%exclude /usr/include/llvm/IR/Mangler.h
%exclude /usr/include/llvm/IR/Metadata.def
%exclude /usr/include/llvm/IR/Metadata.h
%exclude /usr/include/llvm/IR/Module.h
%exclude /usr/include/llvm/IR/ModuleSlotTracker.h
%exclude /usr/include/llvm/IR/ModuleSummaryIndex.h
%exclude /usr/include/llvm/IR/ModuleSummaryIndexYAML.h
%exclude /usr/include/llvm/IR/NoFolder.h
%exclude /usr/include/llvm/IR/OperandTraits.h
%exclude /usr/include/llvm/IR/Operator.h
%exclude /usr/include/llvm/IR/OptBisect.h
%exclude /usr/include/llvm/IR/PassManager.h
%exclude /usr/include/llvm/IR/PassManagerInternal.h
%exclude /usr/include/llvm/IR/PatternMatch.h
%exclude /usr/include/llvm/IR/PredIteratorCache.h
%exclude /usr/include/llvm/IR/ProfileSummary.h
%exclude /usr/include/llvm/IR/SafepointIRVerifier.h
%exclude /usr/include/llvm/IR/Statepoint.h
%exclude /usr/include/llvm/IR/SymbolTableListTraits.h
%exclude /usr/include/llvm/IR/TrackingMDRef.h
%exclude /usr/include/llvm/IR/Type.h
%exclude /usr/include/llvm/IR/TypeBuilder.h
%exclude /usr/include/llvm/IR/TypeFinder.h
%exclude /usr/include/llvm/IR/Use.h
%exclude /usr/include/llvm/IR/UseListOrder.h
%exclude /usr/include/llvm/IR/User.h
%exclude /usr/include/llvm/IR/Value.def
%exclude /usr/include/llvm/IR/Value.h
%exclude /usr/include/llvm/IR/ValueHandle.h
%exclude /usr/include/llvm/IR/ValueMap.h
%exclude /usr/include/llvm/IR/ValueSymbolTable.h
%exclude /usr/include/llvm/IR/Verifier.h
%exclude /usr/include/llvm/IRReader/IRReader.h
%exclude /usr/include/llvm/InitializePasses.h
%exclude /usr/include/llvm/LTO/Caching.h
%exclude /usr/include/llvm/LTO/Config.h
%exclude /usr/include/llvm/LTO/LTO.h
%exclude /usr/include/llvm/LTO/LTOBackend.h
%exclude /usr/include/llvm/LTO/legacy/LTOCodeGenerator.h
%exclude /usr/include/llvm/LTO/legacy/LTOModule.h
%exclude /usr/include/llvm/LTO/legacy/ThinLTOCodeGenerator.h
%exclude /usr/include/llvm/LTO/legacy/UpdateCompilerUsed.h
%exclude /usr/include/llvm/LineEditor/LineEditor.h
%exclude /usr/include/llvm/LinkAllIR.h
%exclude /usr/include/llvm/LinkAllPasses.h
%exclude /usr/include/llvm/Linker/IRMover.h
%exclude /usr/include/llvm/Linker/Linker.h
%exclude /usr/include/llvm/MC/ConstantPools.h
%exclude /usr/include/llvm/MC/LaneBitmask.h
%exclude /usr/include/llvm/MC/MCAsmBackend.h
%exclude /usr/include/llvm/MC/MCAsmInfo.h
%exclude /usr/include/llvm/MC/MCAsmInfoCOFF.h
%exclude /usr/include/llvm/MC/MCAsmInfoDarwin.h
%exclude /usr/include/llvm/MC/MCAsmInfoELF.h
%exclude /usr/include/llvm/MC/MCAsmInfoWasm.h
%exclude /usr/include/llvm/MC/MCAsmLayout.h
%exclude /usr/include/llvm/MC/MCAssembler.h
%exclude /usr/include/llvm/MC/MCCodeEmitter.h
%exclude /usr/include/llvm/MC/MCCodeView.h
%exclude /usr/include/llvm/MC/MCContext.h
%exclude /usr/include/llvm/MC/MCDirectives.h
%exclude /usr/include/llvm/MC/MCDisassembler/MCDisassembler.h
%exclude /usr/include/llvm/MC/MCDisassembler/MCExternalSymbolizer.h
%exclude /usr/include/llvm/MC/MCDisassembler/MCRelocationInfo.h
%exclude /usr/include/llvm/MC/MCDisassembler/MCSymbolizer.h
%exclude /usr/include/llvm/MC/MCDwarf.h
%exclude /usr/include/llvm/MC/MCELFObjectWriter.h
%exclude /usr/include/llvm/MC/MCELFStreamer.h
%exclude /usr/include/llvm/MC/MCExpr.h
%exclude /usr/include/llvm/MC/MCFixedLenDisassembler.h
%exclude /usr/include/llvm/MC/MCFixup.h
%exclude /usr/include/llvm/MC/MCFixupKindInfo.h
%exclude /usr/include/llvm/MC/MCFragment.h
%exclude /usr/include/llvm/MC/MCInst.h
%exclude /usr/include/llvm/MC/MCInstBuilder.h
%exclude /usr/include/llvm/MC/MCInstPrinter.h
%exclude /usr/include/llvm/MC/MCInstrAnalysis.h
%exclude /usr/include/llvm/MC/MCInstrDesc.h
%exclude /usr/include/llvm/MC/MCInstrInfo.h
%exclude /usr/include/llvm/MC/MCInstrItineraries.h
%exclude /usr/include/llvm/MC/MCLabel.h
%exclude /usr/include/llvm/MC/MCLinkerOptimizationHint.h
%exclude /usr/include/llvm/MC/MCMachObjectWriter.h
%exclude /usr/include/llvm/MC/MCObjectFileInfo.h
%exclude /usr/include/llvm/MC/MCObjectStreamer.h
%exclude /usr/include/llvm/MC/MCObjectWriter.h
%exclude /usr/include/llvm/MC/MCParser/AsmCond.h
%exclude /usr/include/llvm/MC/MCParser/AsmLexer.h
%exclude /usr/include/llvm/MC/MCParser/MCAsmLexer.h
%exclude /usr/include/llvm/MC/MCParser/MCAsmParser.h
%exclude /usr/include/llvm/MC/MCParser/MCAsmParserExtension.h
%exclude /usr/include/llvm/MC/MCParser/MCAsmParserUtils.h
%exclude /usr/include/llvm/MC/MCParser/MCParsedAsmOperand.h
%exclude /usr/include/llvm/MC/MCParser/MCTargetAsmParser.h
%exclude /usr/include/llvm/MC/MCRegisterInfo.h
%exclude /usr/include/llvm/MC/MCSchedule.h
%exclude /usr/include/llvm/MC/MCSection.h
%exclude /usr/include/llvm/MC/MCSectionCOFF.h
%exclude /usr/include/llvm/MC/MCSectionELF.h
%exclude /usr/include/llvm/MC/MCSectionMachO.h
%exclude /usr/include/llvm/MC/MCSectionWasm.h
%exclude /usr/include/llvm/MC/MCStreamer.h
%exclude /usr/include/llvm/MC/MCSubtargetInfo.h
%exclude /usr/include/llvm/MC/MCSymbol.h
%exclude /usr/include/llvm/MC/MCSymbolCOFF.h
%exclude /usr/include/llvm/MC/MCSymbolELF.h
%exclude /usr/include/llvm/MC/MCSymbolMachO.h
%exclude /usr/include/llvm/MC/MCSymbolWasm.h
%exclude /usr/include/llvm/MC/MCTargetOptions.h
%exclude /usr/include/llvm/MC/MCTargetOptionsCommandFlags.h
%exclude /usr/include/llvm/MC/MCValue.h
%exclude /usr/include/llvm/MC/MCWasmObjectWriter.h
%exclude /usr/include/llvm/MC/MCWasmStreamer.h
%exclude /usr/include/llvm/MC/MCWin64EH.h
%exclude /usr/include/llvm/MC/MCWinCOFFObjectWriter.h
%exclude /usr/include/llvm/MC/MCWinCOFFStreamer.h
%exclude /usr/include/llvm/MC/MCWinEH.h
%exclude /usr/include/llvm/MC/MachineLocation.h
%exclude /usr/include/llvm/MC/SectionKind.h
%exclude /usr/include/llvm/MC/StringTableBuilder.h
%exclude /usr/include/llvm/MC/SubtargetFeature.h
%exclude /usr/include/llvm/Object/Archive.h
%exclude /usr/include/llvm/Object/ArchiveWriter.h
%exclude /usr/include/llvm/Object/Binary.h
%exclude /usr/include/llvm/Object/COFF.h
%exclude /usr/include/llvm/Object/COFFImportFile.h
%exclude /usr/include/llvm/Object/COFFModuleDefinition.h
%exclude /usr/include/llvm/Object/Decompressor.h
%exclude /usr/include/llvm/Object/ELF.h
%exclude /usr/include/llvm/Object/ELFObjectFile.h
%exclude /usr/include/llvm/Object/ELFTypes.h
%exclude /usr/include/llvm/Object/Error.h
%exclude /usr/include/llvm/Object/IRObjectFile.h
%exclude /usr/include/llvm/Object/IRSymtab.h
%exclude /usr/include/llvm/Object/MachO.h
%exclude /usr/include/llvm/Object/MachOUniversal.h
%exclude /usr/include/llvm/Object/ModuleSymbolTable.h
%exclude /usr/include/llvm/Object/ObjectFile.h
%exclude /usr/include/llvm/Object/RelocVisitor.h
%exclude /usr/include/llvm/Object/StackMapParser.h
%exclude /usr/include/llvm/Object/SymbolSize.h
%exclude /usr/include/llvm/Object/SymbolicFile.h
%exclude /usr/include/llvm/Object/Wasm.h
%exclude /usr/include/llvm/Object/WindowsResource.h
%exclude /usr/include/llvm/ObjectYAML/COFFYAML.h
%exclude /usr/include/llvm/ObjectYAML/CodeViewYAMLDebugSections.h
%exclude /usr/include/llvm/ObjectYAML/CodeViewYAMLSymbols.h
%exclude /usr/include/llvm/ObjectYAML/CodeViewYAMLTypes.h
%exclude /usr/include/llvm/ObjectYAML/DWARFEmitter.h
%exclude /usr/include/llvm/ObjectYAML/DWARFYAML.h
%exclude /usr/include/llvm/ObjectYAML/ELFYAML.h
%exclude /usr/include/llvm/ObjectYAML/MachOYAML.h
%exclude /usr/include/llvm/ObjectYAML/ObjectYAML.h
%exclude /usr/include/llvm/ObjectYAML/WasmYAML.h
%exclude /usr/include/llvm/ObjectYAML/YAML.h
%exclude /usr/include/llvm/Option/Arg.h
%exclude /usr/include/llvm/Option/ArgList.h
%exclude /usr/include/llvm/Option/OptParser.td
%exclude /usr/include/llvm/Option/OptSpecifier.h
%exclude /usr/include/llvm/Option/OptTable.h
%exclude /usr/include/llvm/Option/Option.h
%exclude /usr/include/llvm/Pass.h
%exclude /usr/include/llvm/PassAnalysisSupport.h
%exclude /usr/include/llvm/PassInfo.h
%exclude /usr/include/llvm/PassRegistry.h
%exclude /usr/include/llvm/PassSupport.h
%exclude /usr/include/llvm/Passes/PassBuilder.h
%exclude /usr/include/llvm/ProfileData/Coverage/CoverageMapping.h
%exclude /usr/include/llvm/ProfileData/Coverage/CoverageMappingReader.h
%exclude /usr/include/llvm/ProfileData/Coverage/CoverageMappingWriter.h
%exclude /usr/include/llvm/ProfileData/InstrProf.h
%exclude /usr/include/llvm/ProfileData/InstrProfData.inc
%exclude /usr/include/llvm/ProfileData/InstrProfReader.h
%exclude /usr/include/llvm/ProfileData/InstrProfWriter.h
%exclude /usr/include/llvm/ProfileData/ProfileCommon.h
%exclude /usr/include/llvm/ProfileData/SampleProf.h
%exclude /usr/include/llvm/ProfileData/SampleProfReader.h
%exclude /usr/include/llvm/ProfileData/SampleProfWriter.h
%exclude /usr/include/llvm/Support/AArch64TargetParser.def
%exclude /usr/include/llvm/Support/AMDGPUCodeObjectMetadata.h
%exclude /usr/include/llvm/Support/ARMAttributeParser.h
%exclude /usr/include/llvm/Support/ARMBuildAttributes.h
%exclude /usr/include/llvm/Support/ARMEHABI.h
%exclude /usr/include/llvm/Support/ARMTargetParser.def
%exclude /usr/include/llvm/Support/ARMWinEH.h
%exclude /usr/include/llvm/Support/AlignOf.h
%exclude /usr/include/llvm/Support/Allocator.h
%exclude /usr/include/llvm/Support/ArrayRecycler.h
%exclude /usr/include/llvm/Support/Atomic.h
%exclude /usr/include/llvm/Support/AtomicOrdering.h
%exclude /usr/include/llvm/Support/BinaryByteStream.h
%exclude /usr/include/llvm/Support/BinaryItemStream.h
%exclude /usr/include/llvm/Support/BinaryStream.h
%exclude /usr/include/llvm/Support/BinaryStreamArray.h
%exclude /usr/include/llvm/Support/BinaryStreamError.h
%exclude /usr/include/llvm/Support/BinaryStreamReader.h
%exclude /usr/include/llvm/Support/BinaryStreamRef.h
%exclude /usr/include/llvm/Support/BinaryStreamWriter.h
%exclude /usr/include/llvm/Support/BlockFrequency.h
%exclude /usr/include/llvm/Support/BranchProbability.h
%exclude /usr/include/llvm/Support/CBindingWrapping.h
%exclude /usr/include/llvm/Support/COM.h
%exclude /usr/include/llvm/Support/CachePruning.h
%exclude /usr/include/llvm/Support/Capacity.h
%exclude /usr/include/llvm/Support/Casting.h
%exclude /usr/include/llvm/Support/Chrono.h
%exclude /usr/include/llvm/Support/CodeGen.h
%exclude /usr/include/llvm/Support/CodeGenCWrappers.h
%exclude /usr/include/llvm/Support/CommandLine.h
%exclude /usr/include/llvm/Support/Compiler.h
%exclude /usr/include/llvm/Support/Compression.h
%exclude /usr/include/llvm/Support/ConvertUTF.h
%exclude /usr/include/llvm/Support/CrashRecoveryContext.h
%exclude /usr/include/llvm/Support/DOTGraphTraits.h
%exclude /usr/include/llvm/Support/DataExtractor.h
%exclude /usr/include/llvm/Support/DataTypes.h
%exclude /usr/include/llvm/Support/Debug.h
%exclude /usr/include/llvm/Support/DebugCounter.h
%exclude /usr/include/llvm/Support/DynamicLibrary.h
%exclude /usr/include/llvm/Support/Endian.h
%exclude /usr/include/llvm/Support/EndianStream.h
%exclude /usr/include/llvm/Support/Errc.h
%exclude /usr/include/llvm/Support/Errno.h
%exclude /usr/include/llvm/Support/Error.h
%exclude /usr/include/llvm/Support/ErrorHandling.h
%exclude /usr/include/llvm/Support/ErrorOr.h
%exclude /usr/include/llvm/Support/FileOutputBuffer.h
%exclude /usr/include/llvm/Support/FileSystem.h
%exclude /usr/include/llvm/Support/FileUtilities.h
%exclude /usr/include/llvm/Support/Format.h
%exclude /usr/include/llvm/Support/FormatAdapters.h
%exclude /usr/include/llvm/Support/FormatCommon.h
%exclude /usr/include/llvm/Support/FormatProviders.h
%exclude /usr/include/llvm/Support/FormatVariadic.h
%exclude /usr/include/llvm/Support/FormatVariadicDetails.h
%exclude /usr/include/llvm/Support/FormattedStream.h
%exclude /usr/include/llvm/Support/GCOV.h
%exclude /usr/include/llvm/Support/GenericDomTree.h
%exclude /usr/include/llvm/Support/GenericDomTreeConstruction.h
%exclude /usr/include/llvm/Support/GlobPattern.h
%exclude /usr/include/llvm/Support/GraphWriter.h
%exclude /usr/include/llvm/Support/Host.h
%exclude /usr/include/llvm/Support/JamCRC.h
%exclude /usr/include/llvm/Support/KnownBits.h
%exclude /usr/include/llvm/Support/LEB128.h
%exclude /usr/include/llvm/Support/LICENSE.TXT
%exclude /usr/include/llvm/Support/LineIterator.h
%exclude /usr/include/llvm/Support/Locale.h
%exclude /usr/include/llvm/Support/LockFileManager.h
%exclude /usr/include/llvm/Support/LowLevelTypeImpl.h
%exclude /usr/include/llvm/Support/MD5.h
%exclude /usr/include/llvm/Support/ManagedStatic.h
%exclude /usr/include/llvm/Support/MathExtras.h
%exclude /usr/include/llvm/Support/Memory.h
%exclude /usr/include/llvm/Support/MemoryBuffer.h
%exclude /usr/include/llvm/Support/MipsABIFlags.h
%exclude /usr/include/llvm/Support/Mutex.h
%exclude /usr/include/llvm/Support/MutexGuard.h
%exclude /usr/include/llvm/Support/NativeFormatting.h
%exclude /usr/include/llvm/Support/OnDiskHashTable.h
%exclude /usr/include/llvm/Support/Options.h
%exclude /usr/include/llvm/Support/Parallel.h
%exclude /usr/include/llvm/Support/Path.h
%exclude /usr/include/llvm/Support/PluginLoader.h
%exclude /usr/include/llvm/Support/PointerLikeTypeTraits.h
%exclude /usr/include/llvm/Support/PrettyStackTrace.h
%exclude /usr/include/llvm/Support/Printable.h
%exclude /usr/include/llvm/Support/Process.h
%exclude /usr/include/llvm/Support/Program.h
%exclude /usr/include/llvm/Support/RWMutex.h
%exclude /usr/include/llvm/Support/RandomNumberGenerator.h
%exclude /usr/include/llvm/Support/Recycler.h
%exclude /usr/include/llvm/Support/RecyclingAllocator.h
%exclude /usr/include/llvm/Support/Regex.h
%exclude /usr/include/llvm/Support/Registry.h
%exclude /usr/include/llvm/Support/ReverseIteration.h
%exclude /usr/include/llvm/Support/SHA1.h
%exclude /usr/include/llvm/Support/SMLoc.h
%exclude /usr/include/llvm/Support/SaveAndRestore.h
%exclude /usr/include/llvm/Support/ScaledNumber.h
%exclude /usr/include/llvm/Support/ScopedPrinter.h
%exclude /usr/include/llvm/Support/Signals.h
%exclude /usr/include/llvm/Support/Solaris/sys/regset.h
%exclude /usr/include/llvm/Support/SourceMgr.h
%exclude /usr/include/llvm/Support/SpecialCaseList.h
%exclude /usr/include/llvm/Support/StringPool.h
%exclude /usr/include/llvm/Support/StringSaver.h
%exclude /usr/include/llvm/Support/SwapByteOrder.h
%exclude /usr/include/llvm/Support/SystemUtils.h
%exclude /usr/include/llvm/Support/TarWriter.h
%exclude /usr/include/llvm/Support/TargetParser.h
%exclude /usr/include/llvm/Support/TargetRegistry.h
%exclude /usr/include/llvm/Support/TargetSelect.h
%exclude /usr/include/llvm/Support/ThreadLocal.h
%exclude /usr/include/llvm/Support/ThreadPool.h
%exclude /usr/include/llvm/Support/Threading.h
%exclude /usr/include/llvm/Support/Timer.h
%exclude /usr/include/llvm/Support/ToolOutputFile.h
%exclude /usr/include/llvm/Support/TrailingObjects.h
%exclude /usr/include/llvm/Support/TrigramIndex.h
%exclude /usr/include/llvm/Support/TypeName.h
%exclude /usr/include/llvm/Support/Unicode.h
%exclude /usr/include/llvm/Support/UnicodeCharRanges.h
%exclude /usr/include/llvm/Support/UniqueLock.h
%exclude /usr/include/llvm/Support/VCSRevision.h
%exclude /usr/include/llvm/Support/Valgrind.h
%exclude /usr/include/llvm/Support/Watchdog.h
%exclude /usr/include/llvm/Support/Win64EH.h
%exclude /usr/include/llvm/Support/WindowsError.h
%exclude /usr/include/llvm/Support/YAMLParser.h
%exclude /usr/include/llvm/Support/YAMLTraits.h
%exclude /usr/include/llvm/Support/circular_raw_ostream.h
%exclude /usr/include/llvm/Support/raw_os_ostream.h
%exclude /usr/include/llvm/Support/raw_ostream.h
%exclude /usr/include/llvm/Support/raw_sha1_ostream.h
%exclude /usr/include/llvm/Support/thread.h
%exclude /usr/include/llvm/Support/type_traits.h
%exclude /usr/include/llvm/Support/xxhash.h
%exclude /usr/include/llvm/TableGen/Error.h
%exclude /usr/include/llvm/TableGen/Main.h
%exclude /usr/include/llvm/TableGen/Record.h
%exclude /usr/include/llvm/TableGen/SearchableTable.td
%exclude /usr/include/llvm/TableGen/SetTheory.h
%exclude /usr/include/llvm/TableGen/StringMatcher.h
%exclude /usr/include/llvm/TableGen/StringToOffsetTable.h
%exclude /usr/include/llvm/TableGen/TableGenBackend.h
%exclude /usr/include/llvm/Target/CostTable.h
%exclude /usr/include/llvm/Target/GenericOpcodes.td
%exclude /usr/include/llvm/Target/GlobalISel/RegisterBank.td
%exclude /usr/include/llvm/Target/GlobalISel/SelectionDAGCompat.td
%exclude /usr/include/llvm/Target/GlobalISel/Target.td
%exclude /usr/include/llvm/Target/Target.td
%exclude /usr/include/llvm/Target/TargetCallingConv.h
%exclude /usr/include/llvm/Target/TargetCallingConv.td
%exclude /usr/include/llvm/Target/TargetFrameLowering.h
%exclude /usr/include/llvm/Target/TargetInstrInfo.h
%exclude /usr/include/llvm/Target/TargetIntrinsicInfo.h
%exclude /usr/include/llvm/Target/TargetItinerary.td
%exclude /usr/include/llvm/Target/TargetLowering.h
%exclude /usr/include/llvm/Target/TargetLoweringObjectFile.h
%exclude /usr/include/llvm/Target/TargetMachine.h
%exclude /usr/include/llvm/Target/TargetOpcodes.def
%exclude /usr/include/llvm/Target/TargetOpcodes.h
%exclude /usr/include/llvm/Target/TargetOptions.h
%exclude /usr/include/llvm/Target/TargetRegisterInfo.h
%exclude /usr/include/llvm/Target/TargetSchedule.td
%exclude /usr/include/llvm/Target/TargetSelectionDAG.td
%exclude /usr/include/llvm/Target/TargetSubtargetInfo.h
%exclude /usr/include/llvm/Testing/Support/Error.h
%exclude /usr/include/llvm/Testing/Support/SupportHelpers.h
%exclude /usr/include/llvm/ToolDrivers/llvm-dlltool/DlltoolDriver.h
%exclude /usr/include/llvm/ToolDrivers/llvm-lib/LibDriver.h
%exclude /usr/include/llvm/Transforms/Coroutines.h
%exclude /usr/include/llvm/Transforms/GCOVProfiler.h
%exclude /usr/include/llvm/Transforms/IPO.h
%exclude /usr/include/llvm/Transforms/IPO/AlwaysInliner.h
%exclude /usr/include/llvm/Transforms/IPO/ArgumentPromotion.h
%exclude /usr/include/llvm/Transforms/IPO/ConstantMerge.h
%exclude /usr/include/llvm/Transforms/IPO/CrossDSOCFI.h
%exclude /usr/include/llvm/Transforms/IPO/DeadArgumentElimination.h
%exclude /usr/include/llvm/Transforms/IPO/ElimAvailExtern.h
%exclude /usr/include/llvm/Transforms/IPO/ForceFunctionAttrs.h
%exclude /usr/include/llvm/Transforms/IPO/FunctionAttrs.h
%exclude /usr/include/llvm/Transforms/IPO/FunctionImport.h
%exclude /usr/include/llvm/Transforms/IPO/GlobalDCE.h
%exclude /usr/include/llvm/Transforms/IPO/GlobalOpt.h
%exclude /usr/include/llvm/Transforms/IPO/GlobalSplit.h
%exclude /usr/include/llvm/Transforms/IPO/InferFunctionAttrs.h
%exclude /usr/include/llvm/Transforms/IPO/Inliner.h
%exclude /usr/include/llvm/Transforms/IPO/Internalize.h
%exclude /usr/include/llvm/Transforms/IPO/LowerTypeTests.h
%exclude /usr/include/llvm/Transforms/IPO/PartialInlining.h
%exclude /usr/include/llvm/Transforms/IPO/PassManagerBuilder.h
%exclude /usr/include/llvm/Transforms/IPO/SCCP.h
%exclude /usr/include/llvm/Transforms/IPO/StripDeadPrototypes.h
%exclude /usr/include/llvm/Transforms/IPO/ThinLTOBitcodeWriter.h
%exclude /usr/include/llvm/Transforms/IPO/WholeProgramDevirt.h
%exclude /usr/include/llvm/Transforms/InstCombine/InstCombine.h
%exclude /usr/include/llvm/Transforms/InstCombine/InstCombineWorklist.h
%exclude /usr/include/llvm/Transforms/InstrProfiling.h
%exclude /usr/include/llvm/Transforms/Instrumentation.h
%exclude /usr/include/llvm/Transforms/ObjCARC.h
%exclude /usr/include/llvm/Transforms/PGOInstrumentation.h
%exclude /usr/include/llvm/Transforms/SampleProfile.h
%exclude /usr/include/llvm/Transforms/Scalar.h
%exclude /usr/include/llvm/Transforms/Scalar/ADCE.h
%exclude /usr/include/llvm/Transforms/Scalar/AlignmentFromAssumptions.h
%exclude /usr/include/llvm/Transforms/Scalar/BDCE.h
%exclude /usr/include/llvm/Transforms/Scalar/ConstantHoisting.h
%exclude /usr/include/llvm/Transforms/Scalar/CorrelatedValuePropagation.h
%exclude /usr/include/llvm/Transforms/Scalar/DCE.h
%exclude /usr/include/llvm/Transforms/Scalar/DeadStoreElimination.h
%exclude /usr/include/llvm/Transforms/Scalar/EarlyCSE.h
%exclude /usr/include/llvm/Transforms/Scalar/Float2Int.h
%exclude /usr/include/llvm/Transforms/Scalar/GVN.h
%exclude /usr/include/llvm/Transforms/Scalar/GVNExpression.h
%exclude /usr/include/llvm/Transforms/Scalar/GuardWidening.h
%exclude /usr/include/llvm/Transforms/Scalar/IVUsersPrinter.h
%exclude /usr/include/llvm/Transforms/Scalar/IndVarSimplify.h
%exclude /usr/include/llvm/Transforms/Scalar/JumpThreading.h
%exclude /usr/include/llvm/Transforms/Scalar/LICM.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopAccessAnalysisPrinter.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopDataPrefetch.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopDeletion.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopDistribute.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopIdiomRecognize.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopInstSimplify.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopLoadElimination.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopPassManager.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopPredication.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopRotation.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopSimplifyCFG.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopSink.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopStrengthReduce.h
%exclude /usr/include/llvm/Transforms/Scalar/LoopUnrollPass.h
%exclude /usr/include/llvm/Transforms/Scalar/LowerAtomic.h
%exclude /usr/include/llvm/Transforms/Scalar/LowerExpectIntrinsic.h
%exclude /usr/include/llvm/Transforms/Scalar/LowerGuardIntrinsic.h
%exclude /usr/include/llvm/Transforms/Scalar/MemCpyOptimizer.h
%exclude /usr/include/llvm/Transforms/Scalar/MergedLoadStoreMotion.h
%exclude /usr/include/llvm/Transforms/Scalar/NaryReassociate.h
%exclude /usr/include/llvm/Transforms/Scalar/NewGVN.h
%exclude /usr/include/llvm/Transforms/Scalar/PartiallyInlineLibCalls.h
%exclude /usr/include/llvm/Transforms/Scalar/Reassociate.h
%exclude /usr/include/llvm/Transforms/Scalar/SCCP.h
%exclude /usr/include/llvm/Transforms/Scalar/SROA.h
%exclude /usr/include/llvm/Transforms/Scalar/SimpleLoopUnswitch.h
%exclude /usr/include/llvm/Transforms/Scalar/SimplifyCFG.h
%exclude /usr/include/llvm/Transforms/Scalar/Sink.h
%exclude /usr/include/llvm/Transforms/Scalar/SpeculativeExecution.h
%exclude /usr/include/llvm/Transforms/Scalar/TailRecursionElimination.h
%exclude /usr/include/llvm/Transforms/Utils/ASanStackFrameLayout.h
%exclude /usr/include/llvm/Transforms/Utils/AddDiscriminators.h
%exclude /usr/include/llvm/Transforms/Utils/BasicBlockUtils.h
%exclude /usr/include/llvm/Transforms/Utils/BreakCriticalEdges.h
%exclude /usr/include/llvm/Transforms/Utils/BuildLibCalls.h
%exclude /usr/include/llvm/Transforms/Utils/BypassSlowDivision.h
%exclude /usr/include/llvm/Transforms/Utils/Cloning.h
%exclude /usr/include/llvm/Transforms/Utils/CmpInstAnalysis.h
%exclude /usr/include/llvm/Transforms/Utils/CodeExtractor.h
%exclude /usr/include/llvm/Transforms/Utils/CtorUtils.h
%exclude /usr/include/llvm/Transforms/Utils/EscapeEnumerator.h
%exclude /usr/include/llvm/Transforms/Utils/Evaluator.h
%exclude /usr/include/llvm/Transforms/Utils/FunctionComparator.h
%exclude /usr/include/llvm/Transforms/Utils/FunctionImportUtils.h
%exclude /usr/include/llvm/Transforms/Utils/GlobalStatus.h
%exclude /usr/include/llvm/Transforms/Utils/ImportedFunctionsInliningStatistics.h
%exclude /usr/include/llvm/Transforms/Utils/IntegerDivision.h
%exclude /usr/include/llvm/Transforms/Utils/LCSSA.h
%exclude /usr/include/llvm/Transforms/Utils/LibCallsShrinkWrap.h
%exclude /usr/include/llvm/Transforms/Utils/Local.h
%exclude /usr/include/llvm/Transforms/Utils/LoopSimplify.h
%exclude /usr/include/llvm/Transforms/Utils/LoopUtils.h
%exclude /usr/include/llvm/Transforms/Utils/LoopVersioning.h
%exclude /usr/include/llvm/Transforms/Utils/LowerInvoke.h
%exclude /usr/include/llvm/Transforms/Utils/LowerMemIntrinsics.h
%exclude /usr/include/llvm/Transforms/Utils/Mem2Reg.h
%exclude /usr/include/llvm/Transforms/Utils/ModuleUtils.h
%exclude /usr/include/llvm/Transforms/Utils/NameAnonGlobals.h
%exclude /usr/include/llvm/Transforms/Utils/OrderedInstructions.h
%exclude /usr/include/llvm/Transforms/Utils/PredicateInfo.h
%exclude /usr/include/llvm/Transforms/Utils/PromoteMemToReg.h
%exclude /usr/include/llvm/Transforms/Utils/SSAUpdater.h
%exclude /usr/include/llvm/Transforms/Utils/SSAUpdaterImpl.h
%exclude /usr/include/llvm/Transforms/Utils/SanitizerStats.h
%exclude /usr/include/llvm/Transforms/Utils/SimplifyIndVar.h
%exclude /usr/include/llvm/Transforms/Utils/SimplifyInstructions.h
%exclude /usr/include/llvm/Transforms/Utils/SimplifyLibCalls.h
%exclude /usr/include/llvm/Transforms/Utils/SplitModule.h
%exclude /usr/include/llvm/Transforms/Utils/SymbolRewriter.h
%exclude /usr/include/llvm/Transforms/Utils/UnifyFunctionExitNodes.h
%exclude /usr/include/llvm/Transforms/Utils/UnrollLoop.h
%exclude /usr/include/llvm/Transforms/Utils/VNCoercion.h
%exclude /usr/include/llvm/Transforms/Utils/ValueMapper.h
%exclude /usr/include/llvm/Transforms/Vectorize.h
%exclude /usr/include/llvm/Transforms/Vectorize/LoopVectorize.h
%exclude /usr/include/llvm/Transforms/Vectorize/SLPVectorizer.h
%exclude /usr/include/llvm/XRay/Graph.h
%exclude /usr/include/llvm/XRay/InstrumentationMap.h
%exclude /usr/include/llvm/XRay/Trace.h
%exclude /usr/include/llvm/XRay/XRayRecord.h
%exclude /usr/include/llvm/XRay/YAMLXRayRecord.h
%exclude /usr/lib/BugpointPasses.so
%exclude /usr/lib/LLVMHello.so
%exclude /usr/lib/cmake/llvm/AddLLVM.cmake
%exclude /usr/lib/cmake/llvm/AddLLVMDefinitions.cmake
%exclude /usr/lib/cmake/llvm/AddOCaml.cmake
%exclude /usr/lib/cmake/llvm/AddSphinxTarget.cmake
%exclude /usr/lib/cmake/llvm/CheckAtomic.cmake
%exclude /usr/lib/cmake/llvm/CheckCompilerVersion.cmake
%exclude /usr/lib/cmake/llvm/CheckLinkerFlag.cmake
%exclude /usr/lib/cmake/llvm/ChooseMSVCCRT.cmake
%exclude /usr/lib/cmake/llvm/CrossCompile.cmake
%exclude /usr/lib/cmake/llvm/DetermineGCCCompatible.cmake
%exclude /usr/lib/cmake/llvm/FindOCaml.cmake
%exclude /usr/lib/cmake/llvm/FindSphinx.cmake
%exclude /usr/lib/cmake/llvm/GenerateVersionFromCVS.cmake
%exclude /usr/lib/cmake/llvm/GetSVN.cmake
%exclude /usr/lib/cmake/llvm/HandleLLVMOptions.cmake
%exclude /usr/lib/cmake/llvm/HandleLLVMStdlib.cmake
%exclude /usr/lib/cmake/llvm/LLVM-Config.cmake
%exclude /usr/lib/cmake/llvm/LLVMConfig.cmake
%exclude /usr/lib/cmake/llvm/LLVMConfigVersion.cmake
%exclude /usr/lib/cmake/llvm/LLVMExports-relwithdebinfo.cmake
%exclude /usr/lib/cmake/llvm/LLVMExports.cmake
%exclude /usr/lib/cmake/llvm/LLVMExternalProjectUtils.cmake
%exclude /usr/lib/cmake/llvm/LLVMInstallSymlink.cmake
%exclude /usr/lib/cmake/llvm/LLVMProcessSources.cmake
%exclude /usr/lib/cmake/llvm/TableGen.cmake
%exclude /usr/lib/cmake/llvm/VersionFromVCS.cmake
%exclude /usr/lib/libLLVMAArch64AsmParser.so
%exclude /usr/lib/libLLVMAArch64AsmPrinter.so
%exclude /usr/lib/libLLVMAArch64CodeGen.so
%exclude /usr/lib/libLLVMAArch64Desc.so
%exclude /usr/lib/libLLVMAArch64Disassembler.so
%exclude /usr/lib/libLLVMAArch64Info.so
%exclude /usr/lib/libLLVMAArch64Utils.so
%exclude /usr/lib/libLLVMAMDGPUAsmParser.so
%exclude /usr/lib/libLLVMAMDGPUAsmPrinter.so
%exclude /usr/lib/libLLVMAMDGPUCodeGen.so
%exclude /usr/lib/libLLVMAMDGPUDesc.so
%exclude /usr/lib/libLLVMAMDGPUDisassembler.so
%exclude /usr/lib/libLLVMAMDGPUInfo.so
%exclude /usr/lib/libLLVMAMDGPUUtils.so
%exclude /usr/lib/libLLVMARMAsmParser.so
%exclude /usr/lib/libLLVMARMAsmPrinter.so
%exclude /usr/lib/libLLVMARMCodeGen.so
%exclude /usr/lib/libLLVMARMDesc.so
%exclude /usr/lib/libLLVMARMDisassembler.so
%exclude /usr/lib/libLLVMARMInfo.so
%exclude /usr/lib/libLLVMAnalysis.so
%exclude /usr/lib/libLLVMAsmParser.so
%exclude /usr/lib/libLLVMAsmPrinter.so
%exclude /usr/lib/libLLVMBPFAsmPrinter.so
%exclude /usr/lib/libLLVMBPFCodeGen.so
%exclude /usr/lib/libLLVMBPFDesc.so
%exclude /usr/lib/libLLVMBPFDisassembler.so
%exclude /usr/lib/libLLVMBPFInfo.so
%exclude /usr/lib/libLLVMBinaryFormat.so
%exclude /usr/lib/libLLVMBitReader.so
%exclude /usr/lib/libLLVMBitWriter.so
%exclude /usr/lib/libLLVMCodeGen.so
%exclude /usr/lib/libLLVMCore.so
%exclude /usr/lib/libLLVMCoroutines.so
%exclude /usr/lib/libLLVMCoverage.so
%exclude /usr/lib/libLLVMDebugInfoCodeView.so
%exclude /usr/lib/libLLVMDebugInfoDWARF.so
%exclude /usr/lib/libLLVMDebugInfoMSF.so
%exclude /usr/lib/libLLVMDebugInfoPDB.so
%exclude /usr/lib/libLLVMDemangle.so
%exclude /usr/lib/libLLVMDlltoolDriver.so
%exclude /usr/lib/libLLVMExecutionEngine.so
%exclude /usr/lib/libLLVMGlobalISel.so
%exclude /usr/lib/libLLVMHexagonAsmParser.so
%exclude /usr/lib/libLLVMHexagonCodeGen.so
%exclude /usr/lib/libLLVMHexagonDesc.so
%exclude /usr/lib/libLLVMHexagonDisassembler.so
%exclude /usr/lib/libLLVMHexagonInfo.so
%exclude /usr/lib/libLLVMIRReader.so
%exclude /usr/lib/libLLVMInstCombine.so
%exclude /usr/lib/libLLVMInstrumentation.so
%exclude /usr/lib/libLLVMInterpreter.so
%exclude /usr/lib/libLLVMLTO.so
%exclude /usr/lib/libLLVMLanaiAsmParser.so
%exclude /usr/lib/libLLVMLanaiAsmPrinter.so
%exclude /usr/lib/libLLVMLanaiCodeGen.so
%exclude /usr/lib/libLLVMLanaiDesc.so
%exclude /usr/lib/libLLVMLanaiDisassembler.so
%exclude /usr/lib/libLLVMLanaiInfo.so
%exclude /usr/lib/libLLVMLibDriver.so
%exclude /usr/lib/libLLVMLineEditor.so
%exclude /usr/lib/libLLVMLinker.so
%exclude /usr/lib/libLLVMMC.so
%exclude /usr/lib/libLLVMMCDisassembler.so
%exclude /usr/lib/libLLVMMCJIT.so
%exclude /usr/lib/libLLVMMCParser.so
%exclude /usr/lib/libLLVMMIRParser.so
%exclude /usr/lib/libLLVMMSP430AsmPrinter.so
%exclude /usr/lib/libLLVMMSP430CodeGen.so
%exclude /usr/lib/libLLVMMSP430Desc.so
%exclude /usr/lib/libLLVMMSP430Info.so
%exclude /usr/lib/libLLVMMipsAsmParser.so
%exclude /usr/lib/libLLVMMipsAsmPrinter.so
%exclude /usr/lib/libLLVMMipsCodeGen.so
%exclude /usr/lib/libLLVMMipsDesc.so
%exclude /usr/lib/libLLVMMipsDisassembler.so
%exclude /usr/lib/libLLVMMipsInfo.so
%exclude /usr/lib/libLLVMNVPTXAsmPrinter.so
%exclude /usr/lib/libLLVMNVPTXCodeGen.so
%exclude /usr/lib/libLLVMNVPTXDesc.so
%exclude /usr/lib/libLLVMNVPTXInfo.so
%exclude /usr/lib/libLLVMObjCARCOpts.so
%exclude /usr/lib/libLLVMObject.so
%exclude /usr/lib/libLLVMObjectYAML.so
%exclude /usr/lib/libLLVMOption.so
%exclude /usr/lib/libLLVMOrcJIT.so
%exclude /usr/lib/libLLVMPasses.so
%exclude /usr/lib/libLLVMPowerPCAsmParser.so
%exclude /usr/lib/libLLVMPowerPCAsmPrinter.so
%exclude /usr/lib/libLLVMPowerPCCodeGen.so
%exclude /usr/lib/libLLVMPowerPCDesc.so
%exclude /usr/lib/libLLVMPowerPCDisassembler.so
%exclude /usr/lib/libLLVMPowerPCInfo.so
%exclude /usr/lib/libLLVMProfileData.so
%exclude /usr/lib/libLLVMRuntimeDyld.so
%exclude /usr/lib/libLLVMScalarOpts.so
%exclude /usr/lib/libLLVMSelectionDAG.so
%exclude /usr/lib/libLLVMSparcAsmParser.so
%exclude /usr/lib/libLLVMSparcAsmPrinter.so
%exclude /usr/lib/libLLVMSparcCodeGen.so
%exclude /usr/lib/libLLVMSparcDesc.so
%exclude /usr/lib/libLLVMSparcDisassembler.so
%exclude /usr/lib/libLLVMSparcInfo.so
%exclude /usr/lib/libLLVMSupport.so
%exclude /usr/lib/libLLVMSymbolize.so
%exclude /usr/lib/libLLVMSystemZAsmParser.so
%exclude /usr/lib/libLLVMSystemZAsmPrinter.so
%exclude /usr/lib/libLLVMSystemZCodeGen.so
%exclude /usr/lib/libLLVMSystemZDesc.so
%exclude /usr/lib/libLLVMSystemZDisassembler.so
%exclude /usr/lib/libLLVMSystemZInfo.so
%exclude /usr/lib/libLLVMTableGen.so
%exclude /usr/lib/libLLVMTarget.so
%exclude /usr/lib/libLLVMTransformUtils.so
%exclude /usr/lib/libLLVMVectorize.so
%exclude /usr/lib/libLLVMX86AsmParser.so
%exclude /usr/lib/libLLVMX86AsmPrinter.so
%exclude /usr/lib/libLLVMX86CodeGen.so
%exclude /usr/lib/libLLVMX86Desc.so
%exclude /usr/lib/libLLVMX86Disassembler.so
%exclude /usr/lib/libLLVMX86Info.so
%exclude /usr/lib/libLLVMX86Utils.so
%exclude /usr/lib/libLLVMXCoreAsmPrinter.so
%exclude /usr/lib/libLLVMXCoreCodeGen.so
%exclude /usr/lib/libLLVMXCoreDesc.so
%exclude /usr/lib/libLLVMXCoreDisassembler.so
%exclude /usr/lib/libLLVMXCoreInfo.so
%exclude /usr/lib/libLLVMXRay.so
%exclude /usr/lib/libLLVMipo.so
%exclude /usr/lib/libLTO.so

%files lib
%defattr(-,root,root,-)
/usr/lib/libLLVMAArch64AsmParser.so.5
/usr/lib/libLLVMAArch64AsmParser.so.5.0.1
/usr/lib/libLLVMAArch64AsmPrinter.so.5
/usr/lib/libLLVMAArch64AsmPrinter.so.5.0.1
/usr/lib/libLLVMAArch64CodeGen.so.5
/usr/lib/libLLVMAArch64CodeGen.so.5.0.1
/usr/lib/libLLVMAArch64Desc.so.5
/usr/lib/libLLVMAArch64Desc.so.5.0.1
/usr/lib/libLLVMAArch64Disassembler.so.5
/usr/lib/libLLVMAArch64Disassembler.so.5.0.1
/usr/lib/libLLVMAArch64Info.so.5
/usr/lib/libLLVMAArch64Info.so.5.0.1
/usr/lib/libLLVMAArch64Utils.so.5
/usr/lib/libLLVMAArch64Utils.so.5.0.1
/usr/lib/libLLVMAMDGPUAsmParser.so.5
/usr/lib/libLLVMAMDGPUAsmParser.so.5.0.1
/usr/lib/libLLVMAMDGPUAsmPrinter.so.5
/usr/lib/libLLVMAMDGPUAsmPrinter.so.5.0.1
/usr/lib/libLLVMAMDGPUCodeGen.so.5
/usr/lib/libLLVMAMDGPUCodeGen.so.5.0.1
/usr/lib/libLLVMAMDGPUDesc.so.5
/usr/lib/libLLVMAMDGPUDesc.so.5.0.1
/usr/lib/libLLVMAMDGPUDisassembler.so.5
/usr/lib/libLLVMAMDGPUDisassembler.so.5.0.1
/usr/lib/libLLVMAMDGPUInfo.so.5
/usr/lib/libLLVMAMDGPUInfo.so.5.0.1
/usr/lib/libLLVMAMDGPUUtils.so.5
/usr/lib/libLLVMAMDGPUUtils.so.5.0.1
/usr/lib/libLLVMARMAsmParser.so.5
/usr/lib/libLLVMARMAsmParser.so.5.0.1
/usr/lib/libLLVMARMAsmPrinter.so.5
/usr/lib/libLLVMARMAsmPrinter.so.5.0.1
/usr/lib/libLLVMARMCodeGen.so.5
/usr/lib/libLLVMARMCodeGen.so.5.0.1
/usr/lib/libLLVMARMDesc.so.5
/usr/lib/libLLVMARMDesc.so.5.0.1
/usr/lib/libLLVMARMDisassembler.so.5
/usr/lib/libLLVMARMDisassembler.so.5.0.1
/usr/lib/libLLVMARMInfo.so.5
/usr/lib/libLLVMARMInfo.so.5.0.1
/usr/lib/libLLVMAnalysis.so.5
/usr/lib/libLLVMAnalysis.so.5.0.1
/usr/lib/libLLVMAsmParser.so.5
/usr/lib/libLLVMAsmParser.so.5.0.1
/usr/lib/libLLVMAsmPrinter.so.5
/usr/lib/libLLVMAsmPrinter.so.5.0.1
/usr/lib/libLLVMBPFAsmPrinter.so.5
/usr/lib/libLLVMBPFAsmPrinter.so.5.0.1
/usr/lib/libLLVMBPFCodeGen.so.5
/usr/lib/libLLVMBPFCodeGen.so.5.0.1
/usr/lib/libLLVMBPFDesc.so.5
/usr/lib/libLLVMBPFDesc.so.5.0.1
/usr/lib/libLLVMBPFDisassembler.so.5
/usr/lib/libLLVMBPFDisassembler.so.5.0.1
/usr/lib/libLLVMBPFInfo.so.5
/usr/lib/libLLVMBPFInfo.so.5.0.1
/usr/lib/libLLVMBinaryFormat.so.5
/usr/lib/libLLVMBinaryFormat.so.5.0.1
/usr/lib/libLLVMBitReader.so.5
/usr/lib/libLLVMBitReader.so.5.0.1
/usr/lib/libLLVMBitWriter.so.5
/usr/lib/libLLVMBitWriter.so.5.0.1
/usr/lib/libLLVMCodeGen.so.5
/usr/lib/libLLVMCodeGen.so.5.0.1
/usr/lib/libLLVMCore.so.5
/usr/lib/libLLVMCore.so.5.0.1
/usr/lib/libLLVMCoroutines.so.5
/usr/lib/libLLVMCoroutines.so.5.0.1
/usr/lib/libLLVMCoverage.so.5
/usr/lib/libLLVMCoverage.so.5.0.1
/usr/lib/libLLVMDebugInfoCodeView.so.5
/usr/lib/libLLVMDebugInfoCodeView.so.5.0.1
/usr/lib/libLLVMDebugInfoDWARF.so.5
/usr/lib/libLLVMDebugInfoDWARF.so.5.0.1
/usr/lib/libLLVMDebugInfoMSF.so.5
/usr/lib/libLLVMDebugInfoMSF.so.5.0.1
/usr/lib/libLLVMDebugInfoPDB.so.5
/usr/lib/libLLVMDebugInfoPDB.so.5.0.1
/usr/lib/libLLVMDemangle.so.5
/usr/lib/libLLVMDemangle.so.5.0.1
/usr/lib/libLLVMDlltoolDriver.so.5
/usr/lib/libLLVMDlltoolDriver.so.5.0.1
/usr/lib/libLLVMExecutionEngine.so.5
/usr/lib/libLLVMExecutionEngine.so.5.0.1
/usr/lib/libLLVMGlobalISel.so.5
/usr/lib/libLLVMGlobalISel.so.5.0.1
/usr/lib/libLLVMHexagonAsmParser.so.5
/usr/lib/libLLVMHexagonAsmParser.so.5.0.1
/usr/lib/libLLVMHexagonCodeGen.so.5
/usr/lib/libLLVMHexagonCodeGen.so.5.0.1
/usr/lib/libLLVMHexagonDesc.so.5
/usr/lib/libLLVMHexagonDesc.so.5.0.1
/usr/lib/libLLVMHexagonDisassembler.so.5
/usr/lib/libLLVMHexagonDisassembler.so.5.0.1
/usr/lib/libLLVMHexagonInfo.so.5
/usr/lib/libLLVMHexagonInfo.so.5.0.1
/usr/lib/libLLVMIRReader.so.5
/usr/lib/libLLVMIRReader.so.5.0.1
/usr/lib/libLLVMInstCombine.so.5
/usr/lib/libLLVMInstCombine.so.5.0.1
/usr/lib/libLLVMInstrumentation.so.5
/usr/lib/libLLVMInstrumentation.so.5.0.1
/usr/lib/libLLVMInterpreter.so.5
/usr/lib/libLLVMInterpreter.so.5.0.1
/usr/lib/libLLVMLTO.so.5
/usr/lib/libLLVMLTO.so.5.0.1
/usr/lib/libLLVMLanaiAsmParser.so.5
/usr/lib/libLLVMLanaiAsmParser.so.5.0.1
/usr/lib/libLLVMLanaiAsmPrinter.so.5
/usr/lib/libLLVMLanaiAsmPrinter.so.5.0.1
/usr/lib/libLLVMLanaiCodeGen.so.5
/usr/lib/libLLVMLanaiCodeGen.so.5.0.1
/usr/lib/libLLVMLanaiDesc.so.5
/usr/lib/libLLVMLanaiDesc.so.5.0.1
/usr/lib/libLLVMLanaiDisassembler.so.5
/usr/lib/libLLVMLanaiDisassembler.so.5.0.1
/usr/lib/libLLVMLanaiInfo.so.5
/usr/lib/libLLVMLanaiInfo.so.5.0.1
/usr/lib/libLLVMLibDriver.so.5
/usr/lib/libLLVMLibDriver.so.5.0.1
/usr/lib/libLLVMLineEditor.so.5
/usr/lib/libLLVMLineEditor.so.5.0.1
/usr/lib/libLLVMLinker.so.5
/usr/lib/libLLVMLinker.so.5.0.1
/usr/lib/libLLVMMC.so.5
/usr/lib/libLLVMMC.so.5.0.1
/usr/lib/libLLVMMCDisassembler.so.5
/usr/lib/libLLVMMCDisassembler.so.5.0.1
/usr/lib/libLLVMMCJIT.so.5
/usr/lib/libLLVMMCJIT.so.5.0.1
/usr/lib/libLLVMMCParser.so.5
/usr/lib/libLLVMMCParser.so.5.0.1
/usr/lib/libLLVMMIRParser.so.5
/usr/lib/libLLVMMIRParser.so.5.0.1
/usr/lib/libLLVMMSP430AsmPrinter.so.5
/usr/lib/libLLVMMSP430AsmPrinter.so.5.0.1
/usr/lib/libLLVMMSP430CodeGen.so.5
/usr/lib/libLLVMMSP430CodeGen.so.5.0.1
/usr/lib/libLLVMMSP430Desc.so.5
/usr/lib/libLLVMMSP430Desc.so.5.0.1
/usr/lib/libLLVMMSP430Info.so.5
/usr/lib/libLLVMMSP430Info.so.5.0.1
/usr/lib/libLLVMMipsAsmParser.so.5
/usr/lib/libLLVMMipsAsmParser.so.5.0.1
/usr/lib/libLLVMMipsAsmPrinter.so.5
/usr/lib/libLLVMMipsAsmPrinter.so.5.0.1
/usr/lib/libLLVMMipsCodeGen.so.5
/usr/lib/libLLVMMipsCodeGen.so.5.0.1
/usr/lib/libLLVMMipsDesc.so.5
/usr/lib/libLLVMMipsDesc.so.5.0.1
/usr/lib/libLLVMMipsDisassembler.so.5
/usr/lib/libLLVMMipsDisassembler.so.5.0.1
/usr/lib/libLLVMMipsInfo.so.5
/usr/lib/libLLVMMipsInfo.so.5.0.1
/usr/lib/libLLVMNVPTXAsmPrinter.so.5
/usr/lib/libLLVMNVPTXAsmPrinter.so.5.0.1
/usr/lib/libLLVMNVPTXCodeGen.so.5
/usr/lib/libLLVMNVPTXCodeGen.so.5.0.1
/usr/lib/libLLVMNVPTXDesc.so.5
/usr/lib/libLLVMNVPTXDesc.so.5.0.1
/usr/lib/libLLVMNVPTXInfo.so.5
/usr/lib/libLLVMNVPTXInfo.so.5.0.1
/usr/lib/libLLVMObjCARCOpts.so.5
/usr/lib/libLLVMObjCARCOpts.so.5.0.1
/usr/lib/libLLVMObject.so.5
/usr/lib/libLLVMObject.so.5.0.1
/usr/lib/libLLVMObjectYAML.so.5
/usr/lib/libLLVMObjectYAML.so.5.0.1
/usr/lib/libLLVMOption.so.5
/usr/lib/libLLVMOption.so.5.0.1
/usr/lib/libLLVMOrcJIT.so.5
/usr/lib/libLLVMOrcJIT.so.5.0.1
/usr/lib/libLLVMPasses.so.5
/usr/lib/libLLVMPasses.so.5.0.1
/usr/lib/libLLVMPowerPCAsmParser.so.5
/usr/lib/libLLVMPowerPCAsmParser.so.5.0.1
/usr/lib/libLLVMPowerPCAsmPrinter.so.5
/usr/lib/libLLVMPowerPCAsmPrinter.so.5.0.1
/usr/lib/libLLVMPowerPCCodeGen.so.5
/usr/lib/libLLVMPowerPCCodeGen.so.5.0.1
/usr/lib/libLLVMPowerPCDesc.so.5
/usr/lib/libLLVMPowerPCDesc.so.5.0.1
/usr/lib/libLLVMPowerPCDisassembler.so.5
/usr/lib/libLLVMPowerPCDisassembler.so.5.0.1
/usr/lib/libLLVMPowerPCInfo.so.5
/usr/lib/libLLVMPowerPCInfo.so.5.0.1
/usr/lib/libLLVMProfileData.so.5
/usr/lib/libLLVMProfileData.so.5.0.1
/usr/lib/libLLVMRuntimeDyld.so.5
/usr/lib/libLLVMRuntimeDyld.so.5.0.1
/usr/lib/libLLVMScalarOpts.so.5
/usr/lib/libLLVMScalarOpts.so.5.0.1
/usr/lib/libLLVMSelectionDAG.so.5
/usr/lib/libLLVMSelectionDAG.so.5.0.1
/usr/lib/libLLVMSparcAsmParser.so.5
/usr/lib/libLLVMSparcAsmParser.so.5.0.1
/usr/lib/libLLVMSparcAsmPrinter.so.5
/usr/lib/libLLVMSparcAsmPrinter.so.5.0.1
/usr/lib/libLLVMSparcCodeGen.so.5
/usr/lib/libLLVMSparcCodeGen.so.5.0.1
/usr/lib/libLLVMSparcDesc.so.5
/usr/lib/libLLVMSparcDesc.so.5.0.1
/usr/lib/libLLVMSparcDisassembler.so.5
/usr/lib/libLLVMSparcDisassembler.so.5.0.1
/usr/lib/libLLVMSparcInfo.so.5
/usr/lib/libLLVMSparcInfo.so.5.0.1
/usr/lib/libLLVMSupport.so.5
/usr/lib/libLLVMSupport.so.5.0.1
/usr/lib/libLLVMSymbolize.so.5
/usr/lib/libLLVMSymbolize.so.5.0.1
/usr/lib/libLLVMSystemZAsmParser.so.5
/usr/lib/libLLVMSystemZAsmParser.so.5.0.1
/usr/lib/libLLVMSystemZAsmPrinter.so.5
/usr/lib/libLLVMSystemZAsmPrinter.so.5.0.1
/usr/lib/libLLVMSystemZCodeGen.so.5
/usr/lib/libLLVMSystemZCodeGen.so.5.0.1
/usr/lib/libLLVMSystemZDesc.so.5
/usr/lib/libLLVMSystemZDesc.so.5.0.1
/usr/lib/libLLVMSystemZDisassembler.so.5
/usr/lib/libLLVMSystemZDisassembler.so.5.0.1
/usr/lib/libLLVMSystemZInfo.so.5
/usr/lib/libLLVMSystemZInfo.so.5.0.1
/usr/lib/libLLVMTableGen.so.5
/usr/lib/libLLVMTableGen.so.5.0.1
/usr/lib/libLLVMTarget.so.5
/usr/lib/libLLVMTarget.so.5.0.1
/usr/lib/libLLVMTransformUtils.so.5
/usr/lib/libLLVMTransformUtils.so.5.0.1
/usr/lib/libLLVMVectorize.so.5
/usr/lib/libLLVMVectorize.so.5.0.1
/usr/lib/libLLVMX86AsmParser.so.5
/usr/lib/libLLVMX86AsmParser.so.5.0.1
/usr/lib/libLLVMX86AsmPrinter.so.5
/usr/lib/libLLVMX86AsmPrinter.so.5.0.1
/usr/lib/libLLVMX86CodeGen.so.5
/usr/lib/libLLVMX86CodeGen.so.5.0.1
/usr/lib/libLLVMX86Desc.so.5
/usr/lib/libLLVMX86Desc.so.5.0.1
/usr/lib/libLLVMX86Disassembler.so.5
/usr/lib/libLLVMX86Disassembler.so.5.0.1
/usr/lib/libLLVMX86Info.so.5
/usr/lib/libLLVMX86Info.so.5.0.1
/usr/lib/libLLVMX86Utils.so.5
/usr/lib/libLLVMX86Utils.so.5.0.1
/usr/lib/libLLVMXCoreAsmPrinter.so.5
/usr/lib/libLLVMXCoreAsmPrinter.so.5.0.1
/usr/lib/libLLVMXCoreCodeGen.so.5
/usr/lib/libLLVMXCoreCodeGen.so.5.0.1
/usr/lib/libLLVMXCoreDesc.so.5
/usr/lib/libLLVMXCoreDesc.so.5.0.1
/usr/lib/libLLVMXCoreDisassembler.so.5
/usr/lib/libLLVMXCoreDisassembler.so.5.0.1
/usr/lib/libLLVMXCoreInfo.so.5
/usr/lib/libLLVMXCoreInfo.so.5.0.1
/usr/lib/libLLVMXRay.so.5
/usr/lib/libLLVMXRay.so.5.0.1
/usr/lib/libLLVMipo.so.5
/usr/lib/libLLVMipo.so.5.0.1
/usr/lib/libLTO.so.5
/usr/lib/libLTO.so.5.0.1
